# Generated by Django 3.0.4 on 2021-04-03 04:09

import core.erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, validators=[core.erp.validators.validarLetras], verbose_name='Titulo')),
                ('album', models.CharField(blank=True, max_length=500, null=True, verbose_name='album')),
                ('singer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cantante')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Imagen')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music/%Y/%m/%d', verbose_name='Música')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musica',
                'ordering': ['id'],
            },
        ),
    ]
