# Generated by Django 3.0.4 on 2021-04-03 05:09

import core.erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='price',
            field=models.IntegerField(default=1, null=True, validators=[core.erp.validators.validacionCantidad]),
        ),
    ]
