# Generated by Django 3.0.4 on 2021-04-03 20:56

import core.erp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_music_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, validators=[core.erp.validators.validarLetras], verbose_name='Titulo')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='album')),
            ],
            options={
                'verbose_name': 'Live',
                'verbose_name_plural': 'Lives',
                'ordering': ['id'],
            },
        ),
    ]
