# Generated by Django 3.1.6 on 2021-04-29 23:44

import core.erp.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, validators=[core.erp.validators.validarLetras], verbose_name='Nombres')),
                ('descripcion', models.CharField(max_length=150, unique=True, validators=[core.erp.validators.validarLetras], verbose_name='Descripcion')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('image', models.ImageField(blank=True, upload_to='advertising/%Y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Live',
                'verbose_name_plural': 'Lives',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='live',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.category')),
            ],
        ),
    ]
