# Generated by Django 3.1.6 on 2021-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_live_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='descripcion',
            field=models.CharField(max_length=2000, unique=True, verbose_name='Descripcion'),
        ),
    ]
