# Generated by Django 3.1.6 on 2021-05-01 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0007_auto_20210501_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='usuario'),
            preserve_default=False,
        ),
    ]
